/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\nature.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('/nature.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.portalLight.geometry}
                material={nodes.portalLight.material}
                position={[-11.922, 2.695, -13.218]}
                rotation={[1.573, -0.003, -0.863]}
            />
            <mesh
                geometry={nodes.NTextEmission.geometry}
                material={nodes.NTextEmission.material}
                position={[-11.562, 5.924, -12.815]}
                rotation={[1.231, 0.45, -0.908]}
            />
            <mesh
                geometry={nodes.OTextEmission.geometry}
                material={nodes.OTextEmission.material}
                position={[-11.391, 1.017, -13.81]}
                rotation={[1.6, -0.028, 0.013]}
            />
            <mesh
                geometry={nodes.BTextEmission.geometry}
                material={nodes.BTextEmission.material}
                position={[-12.422, 3.823, -12.086]}
                rotation={[2.124, 1.105, -2.022]}
            />
            <mesh
                geometry={nodes.ZTextEmission.geometry}
                material={nodes.ZTextEmission.material}
                position={[-12.026, 0.939, -11.847]}
                rotation={[1.496, 0.232, -1.978]}
            />
            <mesh
                geometry={nodes.poleLightEmission.geometry}
                material={nodes.poleLightEmission.material}
                position={[3.393, 3.494, 6.507]}
                rotation={[3.068, 0.384, -3.073]}
            />
            <mesh
                geometry={nodes.RuneEmission3.geometry}
                material={nodes.RuneEmission3.material}
                position={[8.214, 2.405, 0.945]}
                rotation={[1.636, -0.035, 1.853]}
            />
            <mesh
                geometry={nodes.RuneEmission1.geometry}
                material={nodes.RuneEmission1.material}
                position={[6.428, 2.217, -6.513]}
                rotation={[1.49, 0.033, 0.413]}
            />
            <mesh
                geometry={nodes.RuneEmission2.geometry}
                material={nodes.RuneEmission2.material}
                position={[8.215, 2.174, -3.332]}
                rotation={[1.679, -0.135, 1.456]}
            />
            <mesh
                geometry={nodes.baked7.geometry}
                material={nodes.baked7.material}
                position={[2.694, 0.601, 0.873]}
                rotation={[-2.438, -0.696, -1.309]}
            />
            <mesh
                geometry={nodes.FireEmber1.geometry}
                material={nodes.FireEmber1.material}
                position={[0, 1.654, 0]}
            />
            <mesh
                geometry={nodes.FireEmitte1.geometry}
                material={nodes.FireEmitte1.material}
                position={[0, 1.055, 0]}
            />
            <mesh
                geometry={nodes.FireEmitter_botom1.geometry}
                material={nodes.FireEmitter_botom1.material}
                position={[0, 0.92, 0]}
            />
            <mesh
                geometry={nodes.FireEmitter_smoke1.geometry}
                material={nodes.FireEmitter_smoke1.material}
                position={[0, 1.761, 0]}
            />
        </group>
    )
}

useGLTF.preload('/nature.glb')
